name: 'blog feed ci'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feed.outputs.changed }}
      items: ${{ steps.feed.outputs.items }}
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: |
            https://note.sarisia.cc/index.xml
            https://zenn.dev/sarisia/feed
            https://qiita.com/sarisia/feed
          file: 'README.md'
          timezone: 'Asia/Tokyo'
          ensure_all: true
      - name: push to master
        if: steps.feed.outputs.changed == true
        id: commit
        uses: sarisia/actions-commit@master
        with:
          message: "docs: update feed"        
      - uses: sarisia/actions-status-discord@v1
        if: failure() || steps.commit.outputs.changed == true
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: update readme with blog feed
  # tweet:
  #   runs-on: ubuntu-latest
  #   needs: readme
  #   if: needs.readme.outputs.changed == true
  #   steps:
  #     - uses: ethomson/send-tweet-action@v1
  #       with:
  #         status: |
  #           New post: ${{ fromJson(needs.readme.outputs.items)[0].title }}
  #           ${{ fromJson(needs.readme.outputs.items)[0].link }}
  #         consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
  #         consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  #         access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  #         access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  #     - uses: sarisia/actions-status-discord@v1
  #       with:
  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: tweet latest entry
